=== sejongmin/XML-Programing/DTD/2/ex7-7.dtd
<!ELEMENT book_catalog (book+)> 
<!ELEMENT book (title, author_group, info, comments?)> 
<!ATTLIST book id CDATA #REQUIRED> 
<!ELEMENT title (#PCDATA)> 
<!ELEMENT author_group (author+)> 
<!ELEMENT author (#PCDATA)> 
<!ATTLIST author number CDATA #IMPLIED> 
<!ELEMENT info (publisher, pub_date, isbn, cover?)> 
<!ELEMENT publisher (#PCDATA)> 
<!ELEMENT pub_date (#PCDATA)> 
<!ELEMENT isbn (#PCDATA)> 
<!ELEMENT cover EMPTY> 
<!ATTLIST cover type (paperback | hardback) "paperback"> 
<!ELEMENT comments (#PCDATA)>

=== sejongmin/XML-Programing/DTD/2/ex7-8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book_catalog SYSTEM "ex7-7.dtd">
<book_catalog>
  <book id="001">
    <title>Creating XML Homepage</title>
    <author_group>
      <author number="1">Jinseok Chae</author>
      <author number="2">Gildong Hong</author>
    </author_group>
    <info>
      <publisher> Honglung Publishing Company</publisher>
      <pub_date>2000-09-10</pub_date>
      <isbn>89-7283-103-4</isbn>
      <cover type="paperback" />
    </info>
    <comments>XML book for beginners</comments>
  </book>
</book_catalog>
