=== sejongmin/XML-Programing/DTD/2/ex7-4.dtd
<!ELEMENT memo (header, body) >
<!ELEMENT header (to, from, date) >
<!ELEMENT to (heading, name) >
<!ATTLIST to 
	age CDATA #REQUIRED
	sex (male | female) "male" >
<!ELEMENT from (heading, name) >
<!ATTLIST from
	age CDATA #REQUIRED
	sex (male | female) "male" >
<!ELEMENT heading (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT date (#PCDATA) >
<!ELEMENT p (#PCDATA) >
<!ELEMENT body (p*) >

=== sejongmin/XML-Programing/DTD/2/ex7-3.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE memo SYSTEM "ex7-4.dtd">

<memo>
  <header>
    <to sex="female">
      <heading>To:</heading>
      <name>Gildong Hong</name>
    </to>
    <from age="35">
      <heading>From:</heading>
      <name>Gilsan Jang</name>
    </from>
    <date> 2004. 4. 15. </date>
  </header>
  <body>
    <p> My First XML Document. </p>
    <p> Hello world! </p>
  </body>
</memo>
