=== sejongmin/XML-Programing/XSD/1/ex8-10.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="memo">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="header"/>
        <xsd:element ref="body"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="header">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="to" type="tofromType"/>
        <xsd:element name="from" type="tofromType"/>
        <xsd:element name="date" type="xsd:date"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="body">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="p" type="xsd:string" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="tofromType">
    <xsd:sequence>
      <xsd:element name="heading" type="xsd:string"/>
      <xsd:element name="name" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="age" type="xsd:integer" use="optional"/>
    <xsd:attribute name="gender" type="genderType" default="male"/>
  </xsd:complexType>
  <xsd:simpleType name="genderType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="male"/>
      <xsd:enumeration value="female"/>
    </xsd:restriction>
  </xsd:simpleType> 
</xsd:schema>

=== sejongmin/XML-Programing/XSD/1/ex8-9.xml
<?xml version="1.0" encoding="UTF-8"?> 
<memo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="ex8-10.xsd">
  <header> 
    <to gender="female">
      <heading>To:</heading>
      <name>Gildong Hong</name>
    </to>
    <from age="35">
      <heading>From:</heading>
      <name>Gilsan Jang</name>
    </from>
    <date>2004-04-15</date>
  </header>
  <body> 
    <p> My First XML Document. </p>
    <p> Hello world! </p>
  </body> 
</memo>
