=== sejongmin/XML-Programing/XSD/1/ex8-8.xsd
<?xml version="1.0" encoding="UTF-8"?> 

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="memo">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="body"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="body">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="pub" type="Publication"/>
        <xsd:element name="single" type="SingleAuthorPublication"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="Publication">
    <xsd:sequence>
      <xsd:element name="Title" type="xsd:string" maxOccurs="unbounded"/>
      <xsd:element name="Author" type="xsd:string" maxOccurs="unbounded"/>
      <xsd:element name="Date" type="xsd:gYear"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name= "SingleAuthorPublication">
    <xsd:complexContent>
      <xsd:restriction base="Publication">
        <xsd:sequence>
          <xsd:element name="Title" type="xsd:string" maxOccurs="unbounded"/>
          <xsd:element name="Author" type="xsd:string"/>
          <xsd:element name="Date" type="xsd:gYear"/>
        </xsd:sequence>
      </xsd:restriction>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== sejongmin/XML-Programing/XSD/1/ex8-7.xml
<?xml version="1.0" encoding="UTF-8"?>

<memo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ex8-8.xsd">
  <body>
    <pub>
      <Title></Title>
      <Author></Author>
      <Author></Author>
      <Author></Author>
      <Date>2020</Date>
    </pub>
    <single>
      <Title></Title>
      <Author></Author>
      <Date>2020</Date>
    </single>
  </body>
</memo>
